import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outfile = "main.js";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@electron/remote",
  ],
  alias: {
    "crypto": "./src/mocks/crypto.ts",
    "node:crypto": "./src/mocks/crypto.ts"
  },
  mainFields: ["module", "main"],
  conditions: ["import"],
  format: "cjs",
  target: "es2015",
  platform: "browser",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
  minify: prod,
});

// Post-build: isolate Dexie global symbol to prevent conflicts with other plugins
function patchDexieSymbol() {
  let code = readFileSync(outfile, "utf8");
  code = code.replace(/Symbol\.for\("Dexie"\)/g, 'Symbol.for("HiLighter-Dexie")');
  writeFileSync(outfile, code);
}

if (prod) {
  await context.rebuild();
  patchDexieSymbol();
  process.exit(0);
} else {
  // For dev/watch mode, we need to patch after each rebuild
  const originalRebuild = context.rebuild.bind(context);
  // Watch mode rebuilds are handled by esbuild's built-in watch
  await context.watch();
}
