import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { join } from 'node:path';

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
(function() {
  window.onerror = function(msg, url, line, col, error) {
    if (msg && msg.indexOf('EME') === -1 && msg.indexOf('plugin') === -1) return;
    var fullMsg = "English Made Easy Error:\\n" + msg + "\\nLine: " + line + "\\nURL: " + url;
    if (window.Notice) { new window.Notice(fullMsg, 10000); }
    else { alert(fullMsg); }
    return false;
  };
  try {
    var g = typeof globalThis !== 'undefined' ? globalThis : 
            typeof window !== 'undefined' ? window : 
            typeof self !== 'undefined' ? self : 
            typeof global !== 'undefined' ? global : {};

    if (typeof g.global === 'undefined') g.global = g;

    // Buffer Polyfill
    if (typeof g.Buffer === 'undefined') {
      try {
        if (typeof require === 'function') {
          try {
            var B = require('buffer/').Buffer;
            if (B) g.Buffer = B;
          } catch (e) {}
        }
      } catch (e) {}
      if (!g.Buffer) {
        g.Buffer = {
          from: function(d) { return typeof d === 'string' ? new g.TextEncoder().encode(d) : new Uint8Array(d); },
          isBuffer: function(o) { return o instanceof Uint8Array; },
          concat: function(a) {
            var l = 0; for (var i = 0; i < a.length; i++) l += a[i].length;
            var r = new Uint8Array(l), o = 0;
            for (var i = 0; i < a.length; i++) { r.set(a[i], o); o += a[i].length; }
            return r;
          },
          alloc: function(s) { return new Uint8Array(s); },
          byteLength: function(d) { return typeof d === 'string' ? new g.TextEncoder().encode(d).length : d.length; }
        };
      }
    }

    // Process Polyfill
    if (typeof g.process === 'undefined') {
      g.process = { env: { NODE_ENV: 'production' }, nextTick: function(f) { setTimeout(f, 0); }, platform: 'browser', cwd: function() { return '/'; }, browser: true };
    } else if (!g.process.env) {
      g.process.env = { NODE_ENV: 'production' };
    }

    // Crypto Polyfill
    if (typeof g.crypto === 'undefined') { try { g.crypto = {}; } catch (e) {} }
    if (g.crypto) {
      if (typeof g.crypto.randomUUID !== 'function') {
        g.crypto.randomUUID = function() {
          return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
            var r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
          });
        };
      }
      if (typeof g.crypto.getRandomValues !== 'function') {
        g.crypto.getRandomValues = function(arr) {
          for (var i = 0; i < arr.length; i++) arr[i] = Math.floor(Math.random() * 256);
          return arr;
        };
      }
    }

    // Modern JS Methods Polyfills
    if (!String.prototype.includes) {
      String.prototype.includes = function(search, start) {
        if (typeof start !== 'number') start = 0;
        if (start + search.length > this.length) return false;
        return this.indexOf(search, start) !== -1;
      };
    }
    if (!Array.prototype.includes) {
      Array.prototype.includes = function(search, start) {
        return this.indexOf(search, start) !== -1;
      };
    }
    if (!Object.assign) {
      Object.assign = function(target) {
        for (var i = 1; i < arguments.length; i++) {
          var source = arguments[i];
          if (source) for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) target[key] = source[key]; }
        }
        return target;
      };
    }
    if (!Object.values) {
      Object.values = function(obj) {
        return Object.keys(obj).map(function(key) { return obj[key]; });
      };
    }
    if (!Object.entries) {
      Object.entries = function(obj) {
        return Object.keys(obj).map(function(key) { return [key, obj[key]]; });
      };
    }
    if (typeof g.TextEncoder === 'undefined') {
      g.TextEncoder = function() {};
      g.TextEncoder.prototype.encode = function(s) {
        var utf8 = unescape(encodeURIComponent(s));
        var res = new Uint8Array(utf8.length);
        for (var i = 0; i < utf8.length; i++) res[i] = utf8.charCodeAt(i);
        return res;
      };
    }
  } catch (e) {
    console.error('[EME] Polyfill initialization failed:', e);
  }
})();
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@electron/remote",
  ],
  alias: {
    "path": "./src/mocks/path.ts",
    "fs": "./src/mocks/fs.ts",
    "crypto": "./src/mocks/crypto.ts",
    "zlib": "./src/mocks/zlib.ts",
    "assert": "./src/mocks/assert.ts",
    "node:path": "./src/mocks/path.ts",
    "node:fs": "./src/mocks/fs.ts",
    "node:crypto": "./src/mocks/crypto.ts",
    "node:zlib": "./src/mocks/zlib.ts",
    "node:assert": "./src/mocks/assert.ts"
  },
  mainFields: ["module", "main"],
  conditions: ["import"],
  format: "cjs",
  target: "es2015",
  platform: "browser",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
